grocery/config/routes.rb
Rails.application.routes.draw do
  resources :lists

	root 'welcome#index'

end

grocery/app/models/list.rb
class List < ActiveRecord::Base
end

grocery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

grocery/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :text, :is_healthy, :complete)
    end
end

grocery/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

grocery/app/helpers/application_helper.rb
module ApplicationHelper
end

grocery/app/helpers/lists_helper.rb
module ListsHelper
end

grocery/app/helpers/welcome_helper.rb
module WelcomeHelper
end

grocery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="groceryApp">
<head>
  <title>Grocery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller="ListCtrl">

<%= yield %>

</body>
</html>

grocery/app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
   <div class="field">
    <%= f.label :is_healthy %><br>
    <%= f.check_box :is_healthy %>
  </div> 
    <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

grocery/app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

grocery/app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <thead>
    <tr>
      <th>Title |</th>
      <th>Description |</th>
      <th>Is healthy</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.text %></td>
        <td><%= list.is_healthy %></td>
        <td><%= list.complete %></td>		
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

grocery/app/views/lists/new.html.erb
<%= form_for :list, url: lists_path do |f| %>  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

grocery/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @list.text %>
</p>
<p>
  <strong>Is healthy:</strong>
  <%= @list.is_healthy %>
</p>
<p>
  <strong>Complete:</strong>
  <%= @list.complete %>
</p>
<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

grocery/app/views/welcome/index.html.erb
<h1>Grocery List</h1>
  <input type="text" ng-model="query"/>
  <input type="checkbox" ng-model="isHealty"/>
  <table class="table table-striped">
    <tr ng-repeat="item in list | filter : {title: query, healthy:isHealty} " ng-class="{ complete: item.complete, healthy: item.healthy }">
      <td><input type="checkbox" ng-click="clicked(item)" ng-checked=" item.complete"></td>
      <td>{{item['title']}}</td>
    </tr>    
  </table>